# IPUMS {#unit2}

## Week 6 Exploratory analysis 
## Week 7 Hypothesis Testing
## Week 8 Statistical Inference
## Week 9 (TBD)
## Week 10 (TBD)

Some text to break up the sub-section headers

## Intro to IPUMS website
### background on ipums
### navigating website

Find certain (very common) variables to answer (common) social science questions.


We describe our methods in this chapter.

Math can be added in body using usual syntax as follows. This may be useful, particularly for explaining the math side of things. 

## math example


$p$ is unknown but expected to be around 1/3. Standard error will be approximated

$$
SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
$$

You can also use math in footnotes like this^[where we mention $p = \frac{a}{b}$]. Footnotes are helpful because they re-link to where you left off.

We will approximate standard error to 0.027[^longnote]

[^longnote]: $p$ is unknown but expected to be around 1/3. Standard error will be approximated

    $$
    SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
    $$

The `longnote` footnote seems particularly useful.
