# Intro/Setup

**NOTE:** chapter templates **do not** require a yaml header (most .RMD docs do). Lay out sections using `#` headers.


# Engage

Brief example of an engaging phenomenon.
  * Poll students and discuss results
    + Does the *average* match up with individual experiences?
  * Real-world research example
  * Interrogating a commonly held assumption
    + the average height of humans is 5'5"


# Explore

Explore other examples of this phenomenon.


Build on the first one to show variation.
  * Other ways to represent the phenomenon/data
    + tabular
    + visually
  * can the example be grouped / broken into subgroups
    + does the same pattern/phenomenon apply?
  * Is there a corollary / inverse phenomenon?


# Explain


Discuss/interrogate the pattern of the data
  * does the shape imply anything
  * try to have it student led / guided
  * with time, students guess at what the data shows/doesn't show without labels

# Elaborate

Work through a new example, contextualizing the phenomenon using real-world data/examples.


# Evaluate/Exercises

 short lab exercises for students to recreate / code in R
 
 Build on past concepts reinforcing basic data maniplutaions, summaries, etc.

