# Unit 3: Independent Research {#unit3}

## Week 11: Students develop research Question
## Week 12: Students find relevant variables from IPUMS
## Week 13: Students test and evaluate results
## Week 14: Students prepare presentations of results
## Week 15: Students present work (slides, poster, podium, etc)

By this point, students should be familiar with basic concepts from Chapter \@ref(unit1). These include:

* Basic Coding
  + read/write data in/out of R
  + basic manipulations
* Theoretical Basis
  + looking at data distributions
  + formal assessment of distributions
  
Students will also be familiar with how these concepts are applied from Chapter \@ref(unit2). Hopefully students will be able to:

* Come up with a social science question they are interested in
  + Critically think about target variable(s) of interest. Any *a priori* covariates? confounders?
  + Acquire relevant data from IPUMS
  + Analyze, Summarize, Visualize Data
    + scope and complexity at student/teach discretion
  + Present research to class
    + **potentially** critically discuss/evaluate each others work. 
    + **science is collaborative** everyone should be out to do their best work and represent the data as best we can. We all have conscious and unconscious biases, and the best way to confront them is share and receive (respectful) feedback.
    
During this Unit, we suggest giving ample class time for independent student research, peer-to-peer collaboration, and basic R/stats troubleshooting. This would also be a great time to model how to give respectful criticism by discussing recent research papers. 
  * We could maybe come up with 1-2 seed examples, with a few talking points

## Example one

## Example two
