
# WHAT IS DATA

# Engage

Brainstorm/word cloud on “what is data”


# Explore
Brainstorm “what do we DO with data”
Brainstorm/word cloud “where do we get data”
We can collect it!
  * quick poll: how many people have ___(participated in a survey? analyzed data?)__
  * XX% of this class has done ____


Pose questions to explore



# Explain - lecture/read

## "what ARE data??"

Data are defined as “facts and statistics collected together for reference or analysis.”1 As seen in Figure 1.1, there are two types of data: quantitative and qualitative. Quantitative data are able to be expressed in numerical format and are countable. These data are either discrete or continuous where discrete data uses numeric bins. For example, we use our age as discrete quantitative data, we round our age to the previous year (eg., 20, 21, 22). Continuous data does not use bins, but rather includes all of the fractions between two whole numbers. An example could be most physical measures like height, weight, the speed at which an individual runs.
Qualitative data describe characteristics or categories and can be broken down into two categories, nominal or ordinal. Nominal data have no inherent ordering but it can be categorized. Examples include country or origin, gender, hair color, race, etc. Ordinal data can both be categorized and ordered (e.g., first, second, and third place is a race).
Going back to our hypothesis of male height on campus, heights are continuous, qualitative data. It is difficult for people to report their specific height and you assume that most individuals will report it rounded to the closest inch. This makes the data you will actually use, discrete quantitative data.


## “what do we DO with data”
### generally compare data and visualize it 

#### examples from recent academic articles

article graphs, citations, instructors research, etc

#### examples from non-academic

customer satisfaction; workplace/department culture; r&D; 


### but really it depends on study design



## Study Design

### Hypothesis/Research Question

###  Or Not! ie exploratory/ “get to know you”


## Study sample

## "HOW do we get data??"

The first step to answering a research question is to collect your data. Broadly, data comes in two forms, primary and secondary. (Fig 1.2) Primary data are data that is collected directly by the researcher. Surveys, observations, experimentation, questionnaires, and interviews are all examples of primary data. Secondary data are collected from published or unpublished literature. It is collected by different researchers and compiled for use by a second scientist. These type of data include data found in published articles, books, journals, biographies, and government records like the US Census.
Once compiled, you now have a data set which is comprised of observations and variables. An observation is all of the measures taken for one person or item. A variable is what is being measured.
The US CDC data is secondary, but you are collecting height data yourself in class as a comparison. The survey or questionnaire you use on your classmates is primary data. Each individual is an observation and the variable of interest is height.



### Types of Data

Just INTRO the ideas here, will follow up more in later lessons/the whole course.

## Study Design Considerations

### Sample vs Population

Is the study sample a representative sample of the population? 

### How to draw samples

Random Sampling: It is a sampling method in which all the items have an equal chance of being selected and the individuals who are selected are just like the ones who are not selected
Stratified Random Sampling: It is a process to gather data by separating the actual population into the distinct subset or strata, and then choosing simple random samples from each stratum Your research question is about the height of all males at your college but recording height data for each individual would be very difficult and time consuming. You instead decide to use a sample of males in your data science class. This is a random sample as each male individual has an equally likely chance of being samples (that is, unless a prerequisite exists).
Sampling strategy can lead to bias. Statistical bias is a systematic tendency which causes differences between results and facts. If instead of your classmates, you had chosen a different sample, like the men’s basketball team, your results would have been biased as basketball players are taller on average.

### Bias 

is there bias in the data?

If so, Be explicit 
Our classroom represents a subset of individuals in this country:
college aged
attending college
specific geography 
specific time period


# Elaborate


**Consider reframing the explanation to quetions**

So we are going to start off this class with a Study
Our study will not have an explicit research question, but rather be a 
“get to know you” survey of this class.

We’re going to collect primary data by asking all students to complete a survey. 
We plan to describe the data and from there may begin toform specific hypotheses to test
Work through the same process/analysis on new data. Either a different 
variable(s) in the same sample, or applying/demonstrating the phenomenon 
using real-world data/examples.


* Reiterate/reinforc the process/task of the lesson
* Does this fit in to other steps/analysis
* does this fit in to other thematic topics?

(Possibly) Build on the first one to show variation.
  * Other ways to represent the phenomenon/data
    + tabular
    + visually



# Evaluate/Exercises

Students complete Short class survey:
Height, Birth Year, Birth Month, Birth Day, academic major/interest, favorite food, favorite color, handedness, hours slept (avg).

Reflect on survey, are there other variables students want to add??
Reflect: How do you plan to use data in your college/grad work. Will you collect primary data? Will you perform a secondary analysis of data? A meta-analysis of previously published studies?



