# Hypothesis Testing - Comparison and Correlations


# Engage

Post-it histogram - height separated by birth month (may require a lot of board space)

Are the distributions similar? different? **too many small samples to tell**?



# Explore

How do we **group** data in order to compare it.

The most simple question in statisitics is:
Is x bigger than y

How can we do that for our groups here?

Summer/Winter?

conduct demo/small-scale experiment/analysis
Ask leading questions, form hypotheses; 
  * can the example be grouped / broken into subgroups
    + does the same pattern/phenomenon apply?
  * Is there a corollary / inverse phenomenon?

Pose questions to explore



Discuss/interrogate the pattern of the data
  * does the shape imply anything
  * try to have it student led / guided
  * with time, students guess at what the data shows/doesn't show without labels



# Explain - lecture/read

demo recode: birth month -> Summer/Winter (daylight-savings or not); 
recode favorite food to sweet/savory

## Why 2 groups?

Historical problem of statistics. We've developed very good methods for very un-reasonable
situations. In order to make these tests work, we often have to **manipulate**
our data in order to meet the **assumptions** of the specific test or analysis
that we'd like to perform.

## Common tests to compare 2 groups
t-test and chisq | box-whisker, histogram, density distribution

## Correlation(s)
correlation (pearson, spearman) | scatter plot
height ~ hrs_slept ; height ~ fav_food_category



TEXT

# Elaborate
demo recode: birth month -> Summer/Winter (daylight-savings or not); recode favorite food to sweet/savory
t-test and chisq | box-whisker, histogram, density distribution
height ~ birth_SW
correlation (pearson, spearman) | scatter plot
height ~ hrs_slept ; height ~ fav_food_category
What is an hypothesis??




# Evaluate/Exercises

Formulate a hypothesis and test it using class survey data.
Recode birth month to birth_quarter; recode favorite food to 3 or more categories
