# Unit 3: Independent Research {-}


Students will select their own research question that can be answered with the IPUMS data set and will spend five weeks conducting a research project complete with data analysis, visualization, and interpretation.


In this section we encourage the instructor to provide ample time for independent student/small-group research. Some class time should be devoted to modeling healthy discussion and critique of methods. Students should learn to discuss not just *how* to answer a research question but *why* they are asking/answering it. What impact does the question/answers have. Is the question releveant/meaningful, and importantly, Is this research question perpetuating racist ideas.

We provide some examples here but encourage instructors (or students) to bring in recent journal/popular articles that do (or do not) apply data science methods well.

## Lesson 11: Students develop research Question {.unlisted .unnumbered}
## Lesson 12: Students find relevant variables from IPUMS {.unlisted .unnumbered}
## Lesson 13: Students test and evaluate results {.unlisted .unnumbered}
## Lesson 14: Students prepare presentations of results {.unlisted .unnumbered}
## Lesson 15: Students present work (slides, poster, podium, etc) {.unlisted .unnumbered}

By this point, students should be familiar with basic concepts from Chapter Unit 1. These include:

* Basic Coding
  + read/write data in/out of R
  + basic manipulations
* Theoretical Basis
  + looking at data distributions
  + formal assessment of distributions
  
Students will also be familiar with how these concepts are applied from Chapter Unit 2. Hopefully students will be able to:

* Come up with a social science question they are interested in
  + Critically think about target variable(s) of interest. Any *a priori* covariates? confounders?
  + Acquire relevant data from IPUMS
  + Analyze, Summarize, Visualize Data
    + scope and complexity at student/teach discretion
  + Present research to class
    + **potentially** critically discuss/evaluate each others work. 
    + **science is collaborative** everyone should be out to do their best work and represent the data as best we can. We all have conscious and unconscious biases, and the best way to confront them is share and receive (respectful) feedback.
    
During this Unit, we suggest giving ample class time for independent student research, peer-to-peer collaboration, and basic R/stats troubleshooting. This would also be a great time to model how to give respectful criticism by discussing recent research papers. 
  * We could maybe come up with 1-2 seed examples, with a few talking points

### Example one

### Example two
