--- 
title: "Data Science for Social Scientists"
subtitle: "An applied course using IPUMS data"
author: 
  - Daniel E. Ehrlich, [IPUMS, University of Minnesota](https://international.ipums.org/international/)
  - Anna Tremblay, [Dept of Soc, Anth, & CJ, Clemson University](https://www.clemson.edu/cbshs/departments/sacj/degrees/anthropology.html)
date: "Compiled on: `r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is an open source book. The output format for this example is bookdown::gitbook."
---

# Preface {-}

An applied methods class for social scientists that uses real-world IPUMS data. This course is:

Open-source and customizable - all materials available on [Github](https://github.com/ehrlichd/stats_book)

Made with open-source tools - [R](https://cran.r-project.org/), [RStudio](https://www.rstudio.com/products/rstudio/), [bookdown](https://bookdown.org/) 

Driven by (nearly) open-source data, harmonized across time and space. - [IPUMS](https://ipums.org)



## What is IPUMS {-}


IPUMS started as a project to digitize the historical records of the US census. It has expanded to include [9 data collections](https://www.ipums.org/), which are united in their methods and principles of making soial science research easier. IPUMS data consists of individual-level census and survey data from more than 100 countries around the world. Notably: 

  * IPUMS **harmonizes** these data, ensuring consistently coded values across time and space.
  * IPUMS provides harmonized **GIS Shapefiles** for most census and survey data.
  * IPUMS provides extensive **metadata**, including:
    + Original questionnaire text
    + Alerts about notable changes in variable definition, universe, or coding
    
    
IPUMS data is free to use for education and research purposes. Researchers just need to register with an **email address** and brief project description. Nothing too formal - we're just trying to understand what kinds of questions researchers are interested in. For educators, we have additional resources to set up [classroom accounts](), making it easy to get your students registered and share IPUMS data with them.



## Why make this course {-}


While we (DEE) may be slightly biased, we think IPUms is a fantastic resource for **Education** and **Research**. Real-world example datasets provide the bulk of the content for this course, providing an **applied context** we hope students (and instructors) will find engaging. We also know meany instructors may be teaching across multiple disciplines, in large departments, or be the only "data person" at their instutition. We think IPUMS data will be useful to virtually any social science field. We provide some example lessons, and encourage instructors to develop their own, using our `template`, to tailor this course to their subject or interest.


# Course Description {-}

This course is broken down into 3, 5-week units. Unit 1 focuses on familiarizing yourself with R and the IPUMS dataset. In Unit 2, each week will showcase a method/analysis using preselected variables. In class, students will walk through a given problem set and produce a lab report by the end of class. In Unit 3, students will work towards answering a research question that they pose, creating a research paper with literature review, data analysis, conclusion, and data outputs.


## Course Aims {-}

Provide students with relevant, hands on, methodological training in data literacy and visualization. 



## Learning Outcomes {-}

After this course, students will be able to:

  * Understand the depth of the IPUMS database and the variables it has to  
offer
  * Compose R code to analyze the IPUMS data
  * Produce visually pleasing data outputs in R
  * Synthesize the information in a written report
  * Present the analysis in a poster format for other students


## Guiding Principles {-}

* Phenomenon-based learning
  + try to start the class with a **question** or **problem**
  + *why* does the data look the way it does
  + structure class so students work towards solving the problem
* Relevant examples
  + Drawn from multiple disciplines (eg, economics, demography)
  + Can be added as modular examples/exercises




# Syllabus - Overview {-}


This syllabus is initially envisioned as 3 5-week sections. However, compilation and content are intended to be modular with templates for instructors to include their own specialties.

The basic structure of this course is:

**Unit 1 (Weeks 1-5):** Understanding and Testing Data

  * Students use simple datasets bundled with the course or provided by the instructor. 
  * Simplified data to illustrate trends.
      + EG: plotting continuous variable (AGE); Table of categorical variable (SEX); Crosstabs

**Unit 2 (Weeks 6-10):** Finding Data and Asking Questions

  * Students begin to analyze real world, IPUMS, datasets, provided by course/instructor.
  * Students begin to model real world phenomena
    + EG: SEX ~ EDUATTAIN ; SEX ~ EDATTAIN + EMPSTAT
  * Students learn to perform exploratory analysis, hypothesis testing, and statistical inference.
  * Students learn to navigate IPUMS website,and find relevant data to thier research interest.
  
**Unit 3 (Weeks 11-15):** Discussing Data and Student Research 

  * Students develop a research question to be answered with IPUMS data.
    + Students are encouraged to fit it to their interests/major/discipline.
  * Course time should be devoted to individual/small-group research.
  * Instructor/class present on recent research.
    + Instructor models constructive / scholarly criticism. 
    + Encourage students to critique published work - responsibly.




## Detailed Syllabus {-}




### Unit 1 Understanding and Testing Data {-}


Students become gain familiarity and comfortability navigating RStudio, coding in R and performing simple data manipulation and visualization exercises. Datasets in this section consist of real-world (or synthetic) data, but the focus is on understanding data types (EG: using Age as a continuous variable; sex, education, employment as categorical; etc). Instructors should acknowledge these as **educational** datasets and make explicit trends found within these data are devoid of context, and must be taken with a (rather large) grain of salt, if at all.


By the end of Unit 1, students will be able to:

* Download R and RStudio
* Read data into R and
* Write (save) data out of R
* Summarize data visually
  + Using `base R`
  + Using `ggplot` (tidyverse)
* Summarize data in tables
  + Using base R
  + Using `gttable` / `tidyverse`
* Formally state and test assumptions of data
  + *EG:* t-test, anova, correlations, regression

By the end of Unit 1, students will understand

* Main types of data
  + *EG:* logical, numeric, character, etc
  + R specic vs general terms
* How to create and describe various data distributions
  + *EG:* normal, poisson, normal-skewed, etc
* Know which types statistical tests are appropriate for a given set of data.




#### Week 1: Intro to R, data types, data structures {-}
#### Week 2: Plotting Data, Distributions{-}
#### Week 3: Statisitcal testing of simple data sets{-}
#### Week 4: Correlation and Relationships of simple data sets {-}
#### Week 5: (TBD) {-}



### Unit 2 Finding Data and Asking Questions (Using IPUMS Data)  {-}

Here we demonstrate two **different** approaches to conducting research. Students become familiar writing up short lab reports detailing their findings. For Section \@ref(exploratory), we/instructor provides students with simple datasets from IPUMS (or other real-world data). Students will learn exploratory data analysis techniques and how to create lab reports to summarize key findings. 

For unit \@ref(hypothesis), students will learn to develop their own simple research questions or social-science hypotheses. They will seek out data to answer these questions, learning to navigate [ipums.org](https://ipums.org), and create **data extracts**, as well as hypothesis-testing statistical methods. Again, lab reports to summarize findings. 

#### Week 6: Intro to IPUMS
#### Week 7: Exploratory analysis {-}


If you've just collected a survey, or other raw data, you may not know what you're looking for. This is perfectly ok but goes against *the scientific method* most people learned in grade school.

This unit begins by presenting data/distributions and asking students to begin interpreting the data . visual exploration is encouraged and basic of data manipulation are taught
  * *EG:* how to subset data, how to reshape data, how to re-code data, how to convert from one `data type` to another.
  
Example lab exercise:

Students given a data set (xls, csv, etc)
  * load data, perform manipulations, basic summaries
    + cross tabs
    + group means by a covariate
  * inspect data visually
    + *DESCRIBE* the distribution - is it normal? significant?
  * *FIND* aquestion in the spread of the data
    + how can you test this (maybe small group work)
  * write up/ present results
    + think on confounding factors / biases

    
#### Week 8: Hypothesis Testing {-}


If, on the other hand you have an a pre-existing idea you want to test. We can follow the traditional *scientific method*. With a question in mind, the first question is: where to look. What better place than [IPUMS](https://ipums.org)!

Begin introducing navigation of web resources - mainly IPUMS international

Students should become comfortable working through lab exercises:
  * Define a question (or be presented with one)
  * Download variables from IPUMS (course downloads possible)
  * Perform a basic analysis (discussed in Unit 1)
  * Generate a **visual argument** for your analysis
    + Include explanation/interpretation/reflection on the question at hand, and the data used
    + Any obvious biases
    + Any obvious confounding factors


#### Week 9: Statistical Inference {-}
#### Week 10: (TBD) {-}





### Unit 3 Discussing Data and Student Research  {-}


Students will select their own research question that can be answered with the IPUMS data set and will spend five weeks conducting a research project complete with data analysis, visualization, and interpretation.


In this section we encourage the instructor to provide ample time for independent student/small-group research. Some class time should be devoted to modeling healthy discussion and critique of methods. Students should learn to discuss not just *how* to answer a research question but *why* they are asking/answering it. What impact does the question/answers have. Is the question releveant/meaningful, and importantly, Is this research question perpetuating racist ideas.

We provide some examples here but encourage instructors (or students) to bring in recent journal/popular articles that do (or do not) apply data science methods well.


#### Week 11: Students develop research Question {-}
#### Week 12: Students find relevant variables from IPUMS {-}
#### Week 13: Students test and evaluate results {-}
#### Week 14: Students prepare presentations of results {-}
#### Week 15: Students present work (slides, poster, podium, etc) {-}







# DEV NOTES {-}

##### TO DO {-}

* Make chapter 1 chapter 2
* Anna Adds chapter con data science intro exclusive of R/IPUMS

* discuss style
  + key terms section for each chapter?
  + key terms in **bold**
  + italics for *emphasis*
  + are we pro-hyphens, or are they pedantic?


##### MISC IDEAS {-}

* Application forward
* Present research/ analysis/results FIRST, then explain the mathematical principals behind it
* daily/weekly “i’m stuck on…” 
  + Students send in questions (night before class) and instructor spends 10-15 mins talking through (or collaboratively working through with class) solutions
  + Alternatively, once a month maybe a longer class covering “common problems asked this month”
daily/weekly “recent research”
* pick out a recent article with good visualization (or bad) and spend 5-10 mins discussing what makes it good (or bad)
  + Encourage students to find articles for extra credit


##### Documentation {-}

This function grabs any packages in your project and adds them to a local list that can be referenced using `R-pacakgename`
  * **NOTE** in practice, that needs to be wrapped in markdown syntax, eg:
    `[@R-bookdown]`
  * See help files for more info - might be able to create/add a `citation` file
    
```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

