
# What *is* data?


## POV:  


> In a social science class, your teacher tells you that the CDC
> reports average male height in the United States to be 69
> inches or 5ft 9in. While browsing dating apps, you notice that
> nearly all the men report that they are 6ft or over. You wonder 
> if this is a bias in reporting, or if the area where you live 
> and attend college has significantly taller men. To test your 
> theory, you want to collect data on height from individuals in 
> your data science class to test if males are truly taller on campus 
> than the country average. 
> 
> **Source:** https://www.cdc.gov/nchs/fastats/body-measurements.htm**


### ACTIVITY - collect data on height

**If in-person**
  * Create a histogram (x axis) on a blackboard/wall, have students place their heights 
  with a post-it note
    + Start with one distribution for whole class
    + Repeat with separate distributions for M/F 
    + _DEE: I want to find a way to acknowledge this dichotomy ignores non-binary individuals, and include some suggestions on how to discuss it._


### ACTIVITY - collect data on birth month

  * Create a histogram (x axis) on a blackboard/wall, have students place their heights 
  with a post-it note
    + Students place post-it notes on month of birth
    
**IDEALLY:** Have both a histogram of height AND histogram of birth month visible
at the same time. Compare/contrast distributions of the two data sets.





## Explore


Questions to consider:
  * *Why do we plot data*
  * *What does the* **distribution** *of post-it notes look like?* 
  * *What can you infer from the distribution(s)*
  * *How does the distribution of height differ from birth month?*





### Example Datasets

If you're working through this course on your own, or are unable to facilitate a classroom activity, see the companion R package, `ipumsED`, which includes example data sets for each lesson, as well as custom code and functions to facilitate learning data science with IPUMS data.

_DEE: This could probably be stated at the begining of unit 1_



### ACTIVITY - Calculate by hand


In our hypothetical setup, we are interested in the **average** height.
  * *What does it mean to be* ***average*** 
  * *Which height would you say is average? (eyeballing)*
  * *Which Birth Month would you say is average? - is there one?*
  
  
Write out steps for calculating **mean** - trivial as it may seem.



## Explain

In the context of this example, we **collected** data on height and birth month for individuals in our class. 
Plotting our data allows us to **visualize** the data, making it easy to interpret.


## Ellaborate

### So what is data?

Data is defined as “facts and statistics collected together for 
reference or analysis.”^[This is from the internet and needs to 
be our words] As seen in Figure 1.1, there are two types of data:
quantitative and qualitative. **Quantitative data** are able to 
be expressed in numerical format and are countable. These data 
are either discrete or continuous where **discrete data** uses 
numeric bins. For example, we use our age as discrete 
quantitative data, we round our age to the previous year (eg., 
20, 21, 22). **Continuous data** does not use bins, but rather 
includes all of the fractions between two whole numbers. An 
example could be most physical measures like height, weight, the 
speed at which an individual runs. 



**Qualitative data** describes characteristics or categories and 
can be broken down into two categories, nominal or ordinal. 
**Nominal data** has no inherent ordering but it can be 
categorized. Examples include country or origin, gender, hair 
color, race, etc. **Ordinal data** can both be categorized and 
ordered (e.g., first, second, and third place is a race).


> Going back to our hypothesis of male height on campus, heights 
> are continuous, qualitative data. It is difficult for people to
> report their specific height and you assume that most 
> individuals will report it rounded to the closest inch. This 
> makes the data you will actually use, discrete quantitative 
> data.



### Collecting Data


The first step to answering a research question is to collect 
your data. Broadly, data comes in two forms, primary and 
secondary. (Fig 1.2) **Primary data** is data that is collected 
directly by the researcher. Surveys, observations, 
experimentation, questionnaires, and interviews are all examples 
of primary data. **Secondary data** is collected from published 
or unpublished literature. It is collected by different 
researchers and compiled for use by a second scientist. This type 
of data includes data found in published articles, books, 
journals, biographies, and government records like the US Census.

Once compiled, you now have a data set which is comprised of 
observations and variables. An **observation** is all of the
measures taken for one person or item. A **variable** is what is 
being measured. 

> The US CDC data is secondary, but you are collecting height 
> data yourself in class as a comparison. The survey or 
> questionnaire you use on your classmates is primary data. Each 
> individual is an observation and the variable of interest is 
> height.


### POPULATIONS AND SAMPLING
 
 
**Random Sampling:** It is a sampling method in which all the 
items have an equal chance of being selected and the individuals 
who are selected are just like the ones who are not selected

**Stratified Random Sampling:** It is a process to gather data by
separating the actual population into the distinct subset or 
strata, and then choosing simple random samples from each stratum
Your research question is about the height of all males at your 
college, but recording height data for each individual would be 
very difficult and time consuming. You instead decide to use a 
sample of males in your data science class. This is a random 
sample as each male individual has an equally likely chance of 
being samples (that is, unless a prerequisite exists).

Sampling strategy can lead to **bias**

> If you had chosen a different sample, like the men’s basketball
> team, your results would have been biased. 


## Evaluation


### Review Questions
  * What is one example of collecting/visualizing data from your own life
  * Is height a **continuous** or **discrete** variable and Why?


### Exercises

Brainstorm 3 topics/questions that are of interest to you personally, or academically.
  * What **variable(s)** will you need to collect to study this phenomenon?
  * Describe these variable(s), are they qualitative or quantitative? Continuous or ordinal?


## Glossary {-}

